### ISSUE TITLE
Issues at decode after finetuning mBART on a monolingual seq2seq task

### ISSUE THREAD

**Issue by gorka96** [prajdabre/yanmtt#11]
Hi!

I finetuned the mBART-large-cc25 model on a paraphrasing dataset for Spanish, with the following command, without any issues:

```
python3 train_nmt.py -n 1 -nr 0 -g 2 \
--model_path models/bartes_paraphrasES \
--is_summarization \
--pretrained_model facebook/mbart-large-cc25 \
--use_official_pretrained \
--tokenizer_name_or_path facebook/mbart-large-cc25 \
--train_slang es_XX \
--train_tlang es_XX \
--dev_slang es_XX \
--dev_tlang es_XX \
--train_src train.src.es_XX \
--train_tgt train.trg.es_XX \
--dev_src test.src.es_XX \
--dev_tgt test.trg.es_XX \
--max_src 128 \
--max_tgt 128 \
--batch_size_indicates_lines \
--batch_size 8 \
--multistep_optimizer_steps 2 \
--num_batches 40000 \
--warmup_steps 20000 \
--no_reload_optimizer_ctr_and_scheduler \
--lr 3e-5 \
--hard_truncate_length 1024 \
--eval_every 555555 \
--no_eval_save_every 555555 \
--shard_files
```

And then I tried to decode some examples:

```
python3 decode_nmt.py -n 1  -nr 0 -g 1 \
--model_path models/bartes_paraphrasES \
--slang es_XX \
--tlang es_XX \
--test_src test.src.es_XX \
--test_tgt decode_es.txt \
--tokenizer_name_or_path facebook/mbart-large-cc25 \
```

But I'm getting the following error:

```                                                                                                                               
IP address is localhost                                                                                                                                                                                    
Tokenizer is: PreTrainedTokenizer(name_or_path='facebook/mbart-large-cc25', vocab_size=250027, model_max_len=1024, is_fast=False, padding_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '<
/s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=True), 'additional_s
pecial_tokens': ['ar_AR', 'cs_CZ', 'de_DE', 'en_XX', 'es_XX', 'et_EE', 'fi_FI', 'fr_XX', 'gu_IN', 'hi_IN', 'it_IT', 'ja_XX', 'kk_KZ', 'ko_KR', 'lt_LT', 'lv_LV', 'my_MM', 'ne_NP', 'nl_XX', 'ro_RO', 'ru_RU
', 'si_LK', 'tr_TR', 'vi_VN', 'zh_CN']})
Running DDP checkpoint example on rank 0.
Tokenizer is: PreTrainedTokenizer(name_or_path='facebook/mbart-large-cc25', vocab_size=250027, model_max_len=1024, is_fast=False, padding_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '<
/s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=True), 'additional_s
pecial_tokens': ['ar_AR', 'cs_CZ', 'de_DE', 'en_XX', 'es_XX', 'et_EE', 'fi_FI', 'fr_XX', 'gu_IN', 'hi_IN', 'it_IT', 'ja_XX', 'kk_KZ', 'ko_KR', 'lt_LT', 'lv_LV', 'my_MM', 'ne_NP', 'nl_XX', 'ro_RO', 'ru_RU
', 'si_LK', 'tr_TR', 'vi_VN', 'zh_CN']})
Running DDP checkpoint example on rank 1.
Using positional embeddings
Using positional embeddings
Using positional embeddings
Using positional embeddings
Remapping layers from parent to child.
Final model dictionary after remapping is: odict_keys(['module.final_logits_bias', 'module.model.shared.weight', 'module.model.encoder.embed_tokens.weight', 'module.model.encoder.embed_positions.weight', ...
.
.
.
'module.model.decoder.layers.11.final_layer_norm.bias', 'module.model.decoder.layernorm_embedding.weight', 'module.model.decoder.layernorm_embedding.bias', 'module.model.decoder.layer_norm.weight', 'module.model.decoder.layer_norm.bias', 'module.lm_head.weight'])
Remapping embeddings.
Eliminating matched params with mismatched sizes from the initial model.
Eliminating module.model.shared.weight
Eliminating module.model.encoder.embed_tokens.weight
Eliminating module.model.encoder.embed_positions.weight
Eliminating module.model.encoder.embed_positions.weight
Eliminating module.model.encoder.layers.0.self_attn.k_proj.weight
Eliminating module.model.encoder.layers.0.self_attn.k_proj.bias
Eliminating module.model.encoder.layers.0.self_attn.v_proj.weight
.
.
.
Eliminating module.model.decoder.layers.5.final_layer_norm.weight
Eliminating module.model.decoder.layers.5.final_layer_norm.bias
Eliminating module.model.decoder.layernorm_embedding.weight
Eliminating module.model.decoder.layernorm_embedding.bias
Eliminating module.model.decoder.layer_norm.weight
Eliminating module.model.decoder.layer_norm.bias
Eliminating module.lm_head.weight
Remapping layers from parent to child.
Final model dictionary after remapping is: odict_keys(['module.final_logits_bias', 'module.model.shared.weight', 'module.model.encoder.embed_tokens.weight', 'module.model.encoder.embed_positions.weight', 'module.model.encoder.layers.0.self_attn.k_proj.weight'
.
.
.
'module.model.decoder.layer_norm.weight', 'module.model.decoder.layer_norm.bias', 'module.lm_head.weight'])
Remapping embeddings.
Eliminating matched params with mismatched sizes from the initial model.
Eliminating module.model.shared.weight
Eliminating module.model.encoder.embed_tokens.weight
Eliminating module.model.encoder.embed_positions.weight
Eliminating module.model.encoder.layers.0.self_attn.k_proj.weight
Eliminating module.model.encoder.layers.0.self_attn.k_proj.bias
.
.
.
Eliminating module.model.decoder.layernorm_embedding.bias
Eliminating module.model.decoder.layer_norm.weight
Eliminating module.model.decoder.layer_norm.bias
Eliminating module.lm_head.weight
Traceback (most recent call last):
  File "decode_nmt.py", line 455, in <module>
    run_demo()
  File "decode_nmt.py", line 451, in run_demo
    mp.spawn(model_create_load_decode, nprocs=args.gpus, args=(args,))         #
  File "/home/gurbizu/BART/yanmtt/bartenv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/gurbizu/BART/yanmtt/bartenv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/gurbizu/BART/yanmtt/bartenv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/gurbizu/BART/yanmtt/bartenv/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/gurbizu/BART/yanmtt/decode_nmt.py", line 124, in model_create_load_decode
    model.load_state_dict(remap_embeddings_eliminate_components_and_eliminate_mismatches(model.state_dict(), remap_layers(checkpoint_dict['model'], 4, args), args), strict=True if (args.remap_encoder == "" and args.remap_decoder == "" and not args.eliminate_encoder_before_initialization and not args.eliminate_decoder_before_initialization and not args.eliminate_embeddings_before_initialization) else False) ## Modification needed if we want to load a partial model trained using multilayer softmaxing.
  File "/home/gurbizu/BART/yanmtt/bartenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
        Missing key(s) in state_dict: "module.model.shared.weight", "module.model.encoder.embed_tokens.weight", "module.model.encoder.embed_positions.weight",
.
.
.
"module.model.decoder.layers.5.final_layer_norm.bias", "module.model.decoder.layernorm_embedding.weight", "module.model.decoder.layernorm_embedding.bias", "module.model.decoder.layer_norm.weight", "module.model.decoder.layer_norm.bias", "module.lm_head.weight".
Unexpected key(s) in state_dict: "module.model.encoder.layers.6.self_attn.k_proj.weight", "module.model.encoder.layers.6.self_attn.k_proj.bias", "module.model.encoder.layers.6.self_attn.v_proj.weight", "module.model.encoder.layers.6.self_attn.v_proj.bias",
.
.
.
"module.model.decoder.layers.11.final_layer_norm.weight", "module.model.decoder.layers.11.final_layer_norm.bias"
```

Any idea what could have caused this? 
am I doing something wrong in the finetune phase? 
or do I need to load the tokenizer on the decode phase in a different way?

Thanks,
Gorka

**Comment by prajdabre** [comment]
Hi Gorka,

If I remember correctly, I never actually specified the command for fine tuning an mbart25 model. Cool that you figured it out.

Ok so a small tweak to the command should work.

--model_path facebook/mbart-cc-25
--use_official_pretrained
--locally_fine_tuned_model_path models/bartes_paraphrasES

Lmk if that works for you.
