### ISSUE TITLE
Problem with Custom Transformers Installation - No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by yash-srivastava19** [prajdabre/yanmtt#59]
Following through the instructions in the repo, there seems to be some problem with the installation of the custom transformers package with the issue : 

`No module named 'setuptools_rust'`

System configs : 
OS : Ubuntu 22.04 LTS

The log produced : 
`... 
Installed /home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/transformers-4.3.2-py3.6.egg
Processing dependencies for transformers==4.3.2
Searching for tokenizers<0.11,>=0.10.1
Reading https://pypi.org/simple/tokenizers/
/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
Downloading https://files.pythonhosted.org/packages/48/2b/b99184cacb1a743edc18290e9127d1b0e658c0c46f2ab5290b27fe865ff4/tokenizers-0.10.3.tar.gz#sha256=1a5d3b596c6d3a237e1ad7f46c472d467b0246be7fd1a364f12576eb8db8f7e6
Best match: tokenizers 0.10.3
Processing tokenizers-0.10.3.tar.gz
Writing /tmp/easy_install-yusrqbr4/tokenizers-0.10.3/setup.cfg
Running tokenizers-0.10.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yusrqbr4/tokenizers-0.10.3/egg-dist-tmp-3955d72l
Traceback (most recent call last):
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-yusrqbr4/tokenizers-0.10.3/setup.py", line 2, in <module>
    #
ModuleNotFoundError: No module named 'setuptools_rust'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 312, in <module>
    cmdclass={"deps_table_update": DepsTableUpdateCommand},
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 124, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 414, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 656, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 703, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 751, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 773, in resolve
    replace_conflicting=replace_conflicting
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1056, in best_match
    return self.obtain(req, installer)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1068, in obtain
    return installer(requirement)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 675, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 701, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1168, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1152, in run_setup
    run_setup(setup_script, args)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 262, in run_setup
    raise
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-yusrqbr4/tokenizers-0.10.3/setup.py", line 2, in <module>
    #
ModuleNotFoundError: No module named 'setuptools_rust'`

Any help with this would be highly appreciated !!!

**Comment by yash-srivastava19** [comment]
I tried installing `setuptools_rust` and the rust compiler - and, after running the command `python setup.py install`, there seems to be some dependency issue with the numpy, as the best match for the numpy version is 1.24.3 , which is incompatible with Python 3.6.8(and the following message is shown) : 

 Extracting transformers-4.3.2-py3.6.egg to /home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages
transformers 4.3.2 is already the active version in easy-install.pth
Installing transformers-cli script to /home/ysriv/PycharmProjects/Intern-YANMTT/venv/bin

Installed /home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/transformers-4.3.2-py3.6.egg
Processing dependencies for transformers==4.3.2
Searching for numpy>=1.17
Reading https://pypi.org/simple/numpy/
/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
Downloading https://files.pythonhosted.org/packages/2c/d4/590ae7df5044465cc9fa2db152ae12468694d62d952b1528ecff328ef7fc/numpy-1.24.3.tar.gz#sha256=ab344f1bf21f140adab8e47fdbc7c35a477dc01408791f8ba00d018dd0bc5155
Best match: numpy 1.24.3
Processing numpy-1.24.3.tar.gz
Writing /tmp/easy_install-lf_xqdl_/numpy-1.24.3/setup.cfg
Running numpy-1.24.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lf_xqdl_/numpy-1.24.3/egg-dist-tmp-e4mrbht4
Traceback (most recent call last):
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/ysriv/PycharmProjects/Intern-YANMTT/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-lf_xqdl_/numpy-1.24.3/setup.py", line 20, in <module>
    1. Change the version in __init__.py, setup.py as well as docs/source/conf.py. Remove the master from the links in
RuntimeError: Python version >= 3.8 required.

During handling of the above exception, another exception occurred ....(Runtime Error Python version >= 3.8 required)

Is the Numpy version be same as that in the requirements file(1.18.5) and how do I make sure that the correct version gets installed, not the incompatible one?
